version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      python: 3.12
      nodejs: 18
    commands:
      - echo "========= Installing Dependencies ========="
      - python -m venv .venv
      - source .venv/bin/activate
      - pip install -r requirements.txt
      - npm install --silent -g serverless
      - echo "Fetching Serverless Access Key from AWS Secrets Manager..."
      - export SERVERLESS_ACCESS_KEY=$(aws secretsmanager get-secret-value --secret-id serverless/access_key --query SecretString --output text)

  pre_build:
    commands:
      - echo "========= Preparing Resources ========="
      - echo "Nothing for now. ."

  build:
    commands:
      - echo "========= Deploying Serverless Application ========="
      - serverless deploy --stage $ENVIRONMENT --region $AWS_REGION --verbose
      - echo "========= Finished Deployment ========="
  post_build:
    commands:
      - echo "========= Deployment Complete ========="
      - echo "Deployment completed on $(date)"

cache:
  paths:
    - .venv/**/*
    - node_modules/**/*
    - .serverless/**/*