version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      python: 3.12
      nodejs: 18
    commands:
      - echo "========= Installing Dependencies ========="
      - python -m venv .venv
      - source .venv/bin/activate
      - pip install -r requirements.txt
      - npm install --silent -g serverless 
      

  pre_build:
    commands:
      - echo "========= Preparing Resources ========="
      - echo "No additional pre-build steps needed for now."

  build:
    commands:
      - echo "========= Deploying Serverless Application ========="
      - export SERVERLESS_ACCESS_KEY=$SERVERLESS_ACCESS_KEY
      - serverless deploy --stage $ENVIRONMENT --region $AWS_REGION --key $SERVERLESS_ACCESS_KEY --verbose
      - echo "finished deployment"
  post_build:
    commands:
      - echo "========= Deployment Complete ========="
      - echo "Deployment completed on $(date)"

cache:
  paths:
    - .venv/**/*
    - node_modules/**/*
    - .serverless/**/*