# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: vinhhvinh
# "service" is the name of this project. This will also be added to your AWS resource names.
service: first-aws-prj

provider:
  name: aws
  runtime: python3.12
  region: ap-southeast-1
  
functions:
  start:
    handler:  go_in.start_phase
    events:
      - httpApi:
          path: /start
          method: get
  end:
    handler:  get_out.end_phase
    events:
      - httpApi:
          path: /end
          method: get
package:
  exclude:
    - venv/**
    - .git/**
    - .serverless/**
    - tests/**
    - docs/**
    - node_modules/**
    - __pycache__/**
